# Generated by Django 2.2.10 on 2020-03-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200306_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teach', to='app.Subject'),
        ),
    ]
