# Generated by Django 2.2.10 on 2020-03-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_teach_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach', to='app.Subject'),
        ),
    ]
