# Generated by Django 2.2.10 on 2020-03-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_bit_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bit', to='app.Member'),
        ),
    ]
