# Generated by Django 2.2.10 on 2020-03-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200310_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit', to='app.Member'),
        ),
    ]
