# Generated by Django 2.2.10 on 2020-03-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200310_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='app.Curriculum')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='app.Member')),
            ],
        ),
    ]
